### PR TITLE
index.html meta tag fixed

### PR DESCRIPTION
**Pull request by vetrivelcsamy**
issue link  #81 

`index.html` meta tag fixed
`src/client/public/index.html`

### CODE REVIEW

**Comment by albseb511** [comment]
Can remove this as well
 - `<link rel="icon" href="%PUBLIC_URL%/favicon.ico" />`

**Comment by vetrivelcsamy** [comment]
can I ask why?

**Comment by vetrivelcsamy** [comment]
> Can remove this as well
> 
> * `<link rel="icon" href="%PUBLIC_URL%/favicon.ico" />`

can I ask why?

**Comment by albseb511** [comment]
the favicon was removed in the commit.

**Comment by vetrivelcsamy** [comment]
@albseb511  nothing removed, I just replaced new favicon [commit Link](https://github.com/masai-oss/execode/pull/83/commits/95d6ced063df8f8894fa87b2736a8d05be19a9e5)

**Pull request merged**
